### PR TITLE
Walk with mutable stop (without step-outs)

### PR DESCRIPTION
**Pull request by critiqjo**
- [x] `NodeMut::walk_mut_simple`
- [x] `CountTree::get_mut`
- [ ] ~~`CountTree::swap`~~ _may be later!_

Alternate names:
- `walk_mut` -> `walk_mut_ex`, `walk_build` or `walk_reshape`
- `walk_mut_simple` -> `walk_mut` or `walk_leak`

~~Have `walk` accept a `stop` closure (then `walk_mut_simple` -> `walk_mut` will be more consistent)?~~ No!

Current renaming:
- `walk_mut` -> `walk_reshape`
- `walk_mut_simple` -> `walk_mut`

### CODE REVIEW

**Comment by critiqjo** [comment]
@kagura-chan r+

**Comment by kagura-chan** [comment]
:pushpin: Commit ca3a1a7 has been approved by `critiqjo`

**Comment by kagura-chan** [comment]
:hourglass: Testing commit ca3a1a7 with merge 4229169...

**Comment by kagura-chan** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/critiqjo/binary-tree/builds/131519365)

**Pull request merged**
