### PR TITLE
Self-balancing CountTree

### PR DESCRIPTION
**Pull request by critiqjo**
Implement and test:
- [x] `insert`
- [x] `push_{front|back}`
- [x] `remove`
- [x] `pop_{front|back}`
- [x] `impl FromIterator`

### CODE REVIEW

**Comment by critiqjo** [comment]
@kagura-chan try

**Comment by critiqjo** [comment]
@kagura-chan try

**Comment by critiqjo** [comment]
@kagura-chan try

**Comment by kagura-chan** [comment]
:hourglass: Trying commit ab0e146 with merge bebc190...

**Comment by critiqjo** [comment]
@kagura-chan try

**Comment by kagura-chan** [comment]
:hourglass: Trying commit ab0e146 with merge 1bb59ee...

**Comment by kagura-chan** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/critiqjo/binary-tree/builds/127988443)

**Comment by critiqjo** [comment]
@kagura-chan r+

**Comment by critiqjo** [comment]
@kagura-chan r+

**Comment by kagura-chan** [comment]
:pushpin: Commit 2646764 has been approved by `critiqjo`

**Comment by kagura-chan** [comment]
:hourglass: Testing commit 2646764 with merge e590bb1...

**Comment by kagura-chan** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/critiqjo/binary-tree/builds/128375918)

**Pull request merged**
