### PR TITLE
Quickcheck testing

### PR DESCRIPTION
**Pull request by critiqjo**

### CODE REVIEW

**Comment by critiqjo** [comment]
@kagura-chan r+

**Comment by kagura-chan** [comment]
:pushpin: Commit 107f068 has been approved by `critiqjo`

**Comment by kagura-chan** [comment]
:hourglass: Testing commit 107f068 with merge dcb102b...

**Comment by kagura-chan** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/critiqjo/binary-tree/builds/129439242)

**Comment by critiqjo** [comment]
@kagura-chan try

**Comment by kagura-chan** [comment]
:hourglass: Trying commit f9969f9 with merge 88bba9f...

**Comment by kagura-chan** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/critiqjo/binary-tree/builds/129445651)

**Comment by critiqjo** [comment]
@kagura-chan r+

**Comment by kagura-chan** [comment]
:pushpin: Commit db411e2 has been approved by `critiqjo`

**Comment by kagura-chan** [comment]
:hourglass: Testing commit db411e2 with merge 459ac85...

**Comment by kagura-chan** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/critiqjo/binary-tree/builds/129446594)

**Pull request merged**
